### ISSUE TITLE
ExtractAlphaParameters called before ExtractCPParameters and accesses invalid memory value

### ISSUE THREAD

**Issue by brentpicasso** [melexis/mlx90641-library#1]
Noticed an error in the library, where the mlx90641->cpAlpha function is accessed before it is set by the function ExtractCPParameters. 
https://github.com/melexis/mlx90641-library/blob/master/functions/MLX90641_API.cpp#L913

The ordering of extraction in MLX90641_ExtractParameters should have ExtractCPParameters before ExtractAlphaParameters so the mlx90641->cpAlpha is correctly set. 

Can you confirm my assessment is correct?  Thank you

**Comment by slavysis** [comment]
Yes, you are right. Thank you very much for the feedback. This should be fixed in the latest release

**Comment by bthebaudeau** [comment]
This has been fixed in commit 6faa8350edd0f3fa018e233d6985687c1af6d40b, so you can close this issue. Thanks.
