### ISSUE TITLE
Broken pixel count array can be overflowed

### ISSUE THREAD

**Issue by brentpicasso** [melexis/mlx90641-library#2]
It appears that this routine can populate the 3rd index of the broken pixel count:

https://github.com/melexis/mlx90641-library/blob/master/functions/MLX90641_API.cpp#L1186

But  the array size is set to 2: 
https://github.com/melexis/mlx90641-library/blob/master/headers/MLX90641_API.h#L49

**Comment by slavysis** [comment]
In practice this should not be possible, but you are right it is possible in theory. This should be fixed in the latest release. Thank you!

Best regards

**Comment by slavysis** [comment]
The MLX90641 has a maximum of 1 defective pixel specified. I re-worked the driver to support just a single pixel to avoid confusion.
Of course it is still possible to apply the algorithm on multiple pixels (if one desires to do so) simply by calling the function multiple times.

Best regards
