### ISSUE TITLE
TBody equation

### ISSUE THREAD

**Issue by jcecconi** [melexis/mlx90641-library#3]
Hi, I'm working with mlx90632 medical version, and I can't find how to calculate TBody (Body Temperature) as melexis software does. Datasheet and libraries only mention how to calculste object temperature, which I can calculate right but it is lower than TBody for near 3°C

**Comment by slavysis** [comment]
This is a question related to the MLX90632 and is not relevant to the MLX90641. The formula you are referring to is normally an IP and not shared.
