### ISSUE TITLE
getImage function does not include the ktaScale and kvScale calculations

### ISSUE THREAD

**Issue by andressmithuis** [melexis/mlx90641-library#5]
The calculation for the getImage function is missing the ktaScale and kvScale adjustments at line 718. The 'raw' kta and kv is used but I get an image as if a light was shining on the lens. Dividing these values by the ktaScale and kvScale results in an image that reflects the scene. 

I'm not sure if the alphaScale also comes into play here. But for now I have an image I can work with. Can someone verify if this alphaScale is also needed in the calculation somewhere?

**Comment by jefftan969** [comment]
I believe the CalculateTo function includes the proper ktaScale, kvScale, and alphaScale calculations

**Comment by slavysis** [comment]
Hi, 
Thanks for noticing the issue with the GetImage function. It is now fixed in the latest update.

Best regards
